name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Check Formatting
        run: bun run format:check

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Run Tests
        run: bun run test

      - name: Build
        run: bun run build
